# Generated by Django 5.0.2 on 2024-03-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_estafado_delete_guru'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuadro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.FloatField(default=0)),
                ('fecha', models.DateTimeField(verbose_name='Creado')),
                ('tecnica', models.CharField(max_length=200)),
            ],
        ),
    ]
