# Generated by Django 5.0.2 on 2024-06-10 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cuadro_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.FloatField(default=0)),
                ('pais', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='api.destino')),
            ],
        ),
    ]
